name: suhol_van_sales
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '3.22.0'

dependencies:
  flutter:
    sdk: flutter

  intl:
  get: ^4.6.6
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  cupertino_icons: ^1.0.6
  connectivity_plus:
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.8
  objectbox: ^4.0.1
  objectbox_flutter_libs: ^4.0.1
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  objectbox_generator: ^4.0.1


flutter:

  uses-material-design: true

  assets:
   - assets/images/

  fonts:
    - family: DMSan-Bold
      fonts:
        - asset: assets/fonts/DMSan-Bold.ttf
    - family: DMSans-Regular
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
    - family: DMSans-SemiBold
      fonts:
        - asset: assets/fonts/DMSans-SemiBold.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf